DROP DATABASE IF EXISTS TreasureHunt;

CREATE DATABASE TreasureHunt;

use TreasureHunt;

CREATE TABLE User (
    Id INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(60) NOT NULL,
    BoxCount INT DEFAULT 6,
    MaxAttempts INT DEFAULT 0,
    PRIMARY KEY (Id)
);

CREATE TABLE Game (
    Id INT NOT NULL AUTO_INCREMENT,
    UserId INT NOT NULL,
    DatePlayed DATE NOT NULL,
    BoxCount INT NOT NULL,
    GuessesUsed INT NOT NULL,
    MaxAttempts INT NOT NULL,
    Victory BOOLEAN NOT NULL,
    FOREIGN KEY (UserId) REFERENCES User(Id),
    PRIMARY KEY (Id)
);